### ISSUE TITLE
Add a tag -> z dictionary for FLARES/EAGLE

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/flares#19]
Add a tag -> z dictionary for FLARES/EAGLE. E.g. dict['002_z009p993'] = 9.993

**Comment by christopherlovell** [comment]
this already exists https://github.com/flaresimulations/flares/blob/master/flares.py#L58

**Comment by stephenmwilkins** [comment]
Can you add for the "PERIODIC" type?
